name: build html modelldcatno

on:
  push:
    branches:
    - master
    paths:
    - ontology/**

jobs:
  build_html:
    runs-on: ubuntu-18.04
    name: html build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: make build directory
      run: |
        mkdir ontology/build

    - name: copy index.html
      uses: canastro/copy-file-action@master
      with:
        source: "ontology/index.html"
        target: "ontology/build/index.html"

    - name: copy modelldcatno.owl
      uses: canastro/copy-file-action@master
      with:
        source: "ontology/modelldcatno.owl"
        target: "ontology/build/modelldcatno.ttl"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: modelldcatno_vocabulary
        publish_dir: ontology/build
